Horizonriver QA20-Mar-2017/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Number__c</fullName>
        <externalId>true</externalId>
        <label>Clinic Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Horizonriver QA20-Mar-2017/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assigned_Groups__c</fullName>
        <label>Assigned Group</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HRSupport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation Support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Email_Send__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Email Send?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Horizonriver QA20-Mar-2017/src/objects/Sub_Case__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Sub_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HRT_CP_IMEI__c</fullName>
        <label>CP IMEI</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_CP_MAC__c</fullName>
        <label>CP MAC</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Carrier__c</fullName>
        <label>Carrier</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Circuit_10__c</fullName>
        <label>Circuit 10</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Circuit_Speed__c</fullName>
        <label>Circuit Speed</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Circuit_Type__c</fullName>
        <label>Circuit Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Cutover_Date__c</fullName>
        <label>Cutover Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HRT_HW_MAC__c</fullName>
        <label>HW MAC</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_HW_Name__c</fullName>
        <label>HW Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_HW_Serial__c</fullName>
        <label>HW Serial #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HRT_Install_Date__c</fullName>
        <label>Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HRT_Is_Task_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Task Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HRT_Modem_Validation_Date__c</fullName>
        <label>Modem Validation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HRT_P4_Install_Date__c</fullName>
        <label>P4 Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HRT_Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Telecom Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Staging Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Field Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Implementation Team I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Implementation Team II</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HRT_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HRT_Support_Pin__c</fullName>
        <label>Support Pin</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_VZ_CARD__c</fullName>
        <label>VZ CARD #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Task</label>
    <nameField>
        <label>Sub Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Horizonriver QA20-Mar-2017/src/classes/CaseTrigger_Test.cls
@isTest(SeeAllData = True)
Public Class CaseTrigger_Test{

    static testmethod void CaseTriggerHandler(){
        Test.starttest();
        Account a = [Select id,Store_Number__c from account order by createddate asc limit 1];
        a.Store_Number__c = '0011';
        update a;
        case c = new case();
        c.Status = 'New';
        c.Origin = 'Email';
        c.Subject = 'Internet carrier for Clinic 0011';
        c.accountid = a.id;
        insert c;
                
        Account ac = [Select id,Store_Number__c from account order by createddate desc limit 1];
        c.Is_Email_Send__c = true;
        c.accountid = ac.id;
        c.Assigned_Groups__c = 'Escalations';
        update c;
        
        Sub_Case__c s = [select id,Case__c,HRT_Stage__c from Sub_Case__c where Case__c =: c.id limit 1];
        Sub_Case__c t = new Sub_Case__c();
        t.id = s.id;
        t.HRT_Status__c = 'Completed';
        t.HRT_Carrier__c = 'test';
        t.HRT_Circuit_10__c = 'test';
        t.HRT_Circuit_Speed__c = 'test';
        t.HRT_Circuit_Type__c = 'test';
        t.HRT_Install_Date__c = system.today();
        t.HRT_Modem_Validation_Date__c = system.today();
        t.HRT_Support_Pin__c = 'test';
        t.HRT_Stage__c = '1 - Telecom Team';
        update t;
        
        t.HRT_Stage__c = '2 - Staging Team';
        t.HRT_Status__c = 'New';
        t.HRT_Is_Task_Completed__c = false;
        t.HRT_HW_Serial__c = 1; 
        t.HRT_HW_Name__c = 'test'; 
        t.HRT_CP_MAC__c = 'test'; 
        t.HRT_CP_IMEI__c = 'test'; 
        t.HRT_VZ_CARD__c =  1;
        t.HRT_HW_MAC__c = 'test'; 
        update t;
        
        t.HRT_Status__c = 'Completed';
        update t;
        
        test.stoptest();
    }
    
    static testmethod void Test2(){
        Test.starttest();
        Account a = [Select id,Store_Number__c from account order by createddate asc limit 1];
        a.Store_Number__c = '0011';
        update a;
        case c = new case();
        c.Status = 'New';
        c.Origin = 'Email';
        c.Subject = 'Internet carrier for Clinic 0011';
        c.accountid = a.id;
        insert c;
                
        Account ac = [Select id,Store_Number__c from account order by createddate desc limit 1];
        c.Is_Email_Send__c = true;
        c.accountid = ac.id;
        c.Assigned_Groups__c = 'Escalations';
        update c;
        
        Sub_Case__c s = [select id,Case__c,HRT_Stage__c from Sub_Case__c where Case__c =: c.id limit 1];
        Sub_Case__c t = new Sub_Case__c();
        t.id = s.id;
        t.HRT_Stage__c = '3 - Field Team';
        t.HRT_Is_Task_Completed__c = false;
        t.HRT_Status__c = 'New';
        t.HRT_P4_Install_Date__c = system.today();
        t.HRT_Cutover_Date__c = system.today();
        update t;
        
        t.HRT_Status__c = 'Completed';
        update t;
        
        t.HRT_Stage__c = '4 - Implementation Team I';
        t.HRT_Is_Task_Completed__c = false;
        t.HRT_Status__c = 'New';
        update t;
        
        t.HRT_Status__c = 'Completed';
        update t;
        
        test.stoptest();
    }

}