Horizonriver QA20-Mar-2017/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>HRT_Account_Email__c</fullName>
        <label>Account Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>HRT_Case_Stage__c</fullName>
        <label>Case Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Telecom Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Staging Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Field Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Implementation Team I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Implementation Team II</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Horizonriver QA20-Mar-2017/src/objects/Custom_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email_Queue_Name__c</fullName>
        <label>Email_Queue_Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Queue__c</fullName>
        <label>Email_Queue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_ToAdd__c</fullName>
        <label>Email_ToAdd</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Custom Config</label>
</CustomObject>

Horizonriver QA20-Mar-2017/src/objects/Implementation__c.object
<CustomObject>
    <fields>
        <fullName>CP_IMEI__c</fullName>
        <label>CP IMEI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CP_MAC__c</fullName>
        <label>CP MAC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Circuit_10__c</fullName>
        <label>Circuit 10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circuit_Speed__c</fullName>
        <label>Circuit Speed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circuit_Type__c</fullName>
        <label>Circuit Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cutover_Date__c</fullName>
        <label>Cutover Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cutover_Process_Completion_Date__c</fullName>
        <label>Cutover Process Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HW_MAC__c</fullName>
        <label>HW MAC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HW_Name__c</fullName>
        <label>HW Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HW_Serial__c</fullName>
        <label>HW Serial #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Date__c</fullName>
        <label>Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Modem_Validation_Date__c</fullName>
        <label>Modem Validation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>P4_Install_Date__c</fullName>
        <label>P4 Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site_Survey__c</fullName>
        <label>Site Survey</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Support_Pin__c</fullName>
        <label>Support Pin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VZ_CARD__c</fullName>
        <label>VZ CARD #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Implementation</label>
    <nameField>
        <label>Implementation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Horizonriver QA20-Mar-2017/src/objects/Sub_Case__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Sub_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HRT_Account_Email__c</fullName>
        <label>Account Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>HRT_CP_IMEI__c</fullName>
        <label>CP IMEI</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_CP_MAC__c</fullName>
        <label>CP MAC</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Carrier__c</fullName>
        <label>Carrier</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Circuit_10__c</fullName>
        <label>Circuit 10</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Circuit_Speed__c</fullName>
        <label>Circuit Speed</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Circuit_Type__c</fullName>
        <label>Circuit Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Cutover_Date__c</fullName>
        <label>Cutover Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HRT_Cutover_process_completion_date__c</fullName>
        <label>Cutover Process Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HRT_HW_MAC__c</fullName>
        <label>HW MAC</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_HW_Name__c</fullName>
        <label>HW Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_HW_Serial__c</fullName>
        <label>HW Serial #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HRT_Install_Date__c</fullName>
        <label>Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HRT_Modem_Validation_Date__c</fullName>
        <label>Modem Validation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HRT_P4_Install_Date__c</fullName>
        <label>P4 Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HRT_Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HRT_Site_Survey__c</fullName>
        <label>Site Survey</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Telecom Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Staging Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Field Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Implementation Team I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Implementation Team II</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HRT_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HRT_Support_Pin__c</fullName>
        <label>Support Pin</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HRT_VZ_CARD__c</fullName>
        <label>VZ CARD #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Task</label>
    <nameField>
        <label>Sub Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Horizonriver QA20-Mar-2017/src/classes/SubCaseTriggerHandler.cls
Public class SubCaseTriggerHandler{
    
    Public Static boolean flg = true;
    
    public void Isupdate(Map<id,Sub_Case__c> NewMap, Map<id,Sub_Case__c> OldMap){
        if(Test.isrunningtest()|| flg){
        UpdateImp(NewMap);
        CreateTask(NewMap,OldMap);   
        }     
    }
    
    //update Implementation
    public void UpdateImp(Map<id,Sub_Case__c> NewMap){
        List<id> cid = new List<id>();
        For(Sub_Case__c c : NewMap.values()){
            cid.add(c.Case__c);
        }
        
        Map<id,id> impmap = new Map<id,id>();
        For(Implementation__c i : [Select id,Case__c from Implementation__c where Case__c =: cid]){
            impmap.put(i.Case__c,i.id);
        }
        
        if(impmap.size()>0){
            List<Implementation__c> implst = new List<Implementation__c>();
            Set<id> temp = new Set<id>();
            Implementation__c i = new Implementation__c(); 
            For(Sub_Case__c c : NewMap.values()){
                
                   
                    if(c.HRT_Stage__c == '1 - Telecom Team'){
                        i.Carrier__c = c.HRT_Carrier__c;
                        i.Circuit_10__c = c.HRT_Circuit_10__c;
                        i.Circuit_Speed__c = c.HRT_Circuit_Speed__c;
                        i.Circuit_Type__c = c.HRT_Circuit_Type__c;
                        i.Install_Date__c = c.HRT_Install_Date__c;
                        i.Modem_Validation_Date__c = c.HRT_Modem_Validation_Date__c;
                        i.Support_Pin__c = c.HRT_Support_Pin__c;
                    }
                    if(c.HRT_Stage__c == '2 - Staging Team'){
                        i.CP_MAC__c = c.HRT_HW_MAC__c;
                        i.HW_Name__c = c.HRT_HW_Name__c;
                        i.HW_Serial__c = c.HRT_HW_Serial__c;
                        i.CP_IMEI__c = c.HRT_CP_IMEI__c;
                        i.HW_MAC__c = c.HRT_CP_MAC__c;
                        i.VZ_CARD__c = c.HRT_VZ_CARD__c;
                    }
                    if(c.HRT_Stage__c == '3 - Field Team'){
                        i.P4_Install_Date__c = c.HRT_P4_Install_Date__c;
                    }
                    if(c.HRT_Stage__c == '4 - Implementation Team I'){
                        i.Cutover_Date__c = c.HRT_Cutover_Date__c;
                        i.Site_Survey__c = c.HRT_Site_Survey__c;
                    }
                    if(c.HRT_Stage__c == '5 - Implementation Team II'){
                        i.Cutover_Process_Completion_Date__c = c.HRT_Cutover_process_completion_date__c;
                    }
                    if(impmap.containskey(c.Case__c) && !(temp.contains(c.Case__c))){
                        i.id = impmap.get(c.Case__c);
                        temp.add(c.Case__c);
                        
                    }
            }
            implst.add(i);
            
            if(implst.size()>0)
                update implst;
        }
  }
    
    //Task: Case Management - Task Creation
    public void CreateTask(Map<id,Sub_Case__c> NewMap, Map<id,Sub_Case__c> OldMap){
        flg = false;
        List<Sub_Case__c> TkCreate = new List<Sub_Case__c>();
        List<Case> CaseUpdate= new List<Case>();
        List<Case> CaseUpdate2= new List<Case>();
        Map<string,Custom_Config__c> QMap = new Map<string,Custom_Config__c>();
        For(Custom_Config__c c : [SELECT Id, Email_ToAdd__c, Email_Queue__c,Email_Queue_Name__c FROM Custom_Config__c where Email_Queue_Name__c != null and Email_Queue__c != null ]){
            QMap.put(c.Email_Queue_Name__c,c);
        }
        
        For(Sub_Case__c c : NewMap.values()){
            
            
            if(c.HRT_Stage__c == '1 - Telecom Team' && c.HRT_Status__c != 'New' && c.HRT_Status__c!= OldMap.get(c.id).HRT_Status__c){
            Case s = new Case();
            s.id = c.Case__c;
            s.status = 'InProgress';
            CaseUpdate2.add(s);
            }
            
        
            if(c.HRT_Status__c== 'Completed' && c.HRT_Status__c!= OldMap.get(c.id).HRT_Status__c){
                system.debug('==>'+c.name);
                Sub_Case__c t = new Sub_Case__c();
                Case s = new Case();
                t.HRT_Status__c = 'New';
                t.HRT_Priority__c = 'Medium';
                if(c.HRT_Stage__c == '1 - Telecom Team'){
                    t.Name = 'Order Submit to Warehouse';
                    t.HRT_Stage__c = '2 - Staging Team';
                    t.Recordtypeid = Schema.SObjectType.Sub_Case__c.getRecordTypeInfosByName().get('Task 2 - Staging Team').getRecordTypeId();
                    s.HRT_Case_Stage__c = '2 - Staging Team';
                    if(QMap.containskey('2 - Staging Team'))
                    t.ownerid = QMap.get('2 - Staging Team').Email_Queue__c;
                    t.HRT_Account_Email__c = c.HRT_Account_Email__c;
                }
                if(c.HRT_Stage__c == '2 - Staging Team'){
                    t.Name = 'CS Tech Integration Submission - Get SR';
                    t.HRT_Stage__c = '3 - Field Team';
                    t.Recordtypeid = Schema.SObjectType.Sub_Case__c.getRecordTypeInfosByName().get('Task 3 - CS Tech Integration Sub').getRecordTypeId();
                    s.HRT_Case_Stage__c = '3 - Field Team';
                    if(QMap.containskey('3 - Field Team'))
                    t.ownerid = QMap.get('3 - Field Team').Email_Queue__c;
                    t.HRT_Account_Email__c = c.HRT_Account_Email__c;
                }
                if(c.HRT_Stage__c == '3 - Field Team'){
                    t.Name = 'CS Tech';
                    t.HRT_Stage__c = '4 - Implementation Team I';
                    t.Recordtypeid = Schema.SObjectType.Sub_Case__c.getRecordTypeInfosByName().get('Task 4 - CS Tech').getRecordTypeId();
                    s.HRT_Case_Stage__c = '4 - Implementation Team I';
                    if(QMap.containskey('4 - Implementation Team I'))
                    t.ownerid = QMap.get('4 - Implementation Team I').Email_Queue__c;
                    t.HRT_Account_Email__c = c.HRT_Account_Email__c;
                }
                if(c.HRT_Stage__c == '4 - Implementation Team I'){
                    t.name = 'Review Survey Results';
                    t.HRT_Stage__c = '5 - Implementation Team II';
                    t.Recordtypeid = Schema.SObjectType.Sub_Case__c.getRecordTypeInfosByName().get('Task 5 - Review Survey Results').getRecordTypeId();
                    s.HRT_Case_Stage__c = '5 - Implementation Team II';
                    if(QMap.containskey('5 - Implementation Team II'))
                    t.ownerid = QMap.get('5 - Implementation Team II').Email_Queue__c;
                    t.HRT_Account_Email__c = c.HRT_Account_Email__c;
                }
                if(c.HRT_Stage__c == '5 - Implementation Team II'){
                    s.Reason = 'All Task Completed';
                    s.Status = 'Closed';
                }
                t.Case__c = c.Case__c ;//caseid
                s.id = c.Case__c;
                if(!(c.HRT_Stage__c == '5 - Implementation Team II'))
                TkCreate.add(t);
                CaseUpdate.add(s);
            }
        }
        
        if(TkCreate.size()>0)
            insert TkCreate;
        if(CaseUpdate.size()>0)
            update CaseUpdate;  
        if(CaseUpdate2.size()>0)
            update CaseUpdate2;  
    
        
    }
}