Horizonriver QA20-Mar-2017/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>DS_Envelope_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DocuSign Envelope</label>
        <referenceTo>dsfs__DocuSign_Envelope__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocusignStatus__c</fullName>
        <label>Docusign Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentTerms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 30 Days</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QuoteFrom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote From</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <formula>Opportunity.Account.BillingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zip Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Horizonriver PRD21-Mar-2017/src/objects/Quote.object
    <fields>
        <fullName>Sub_Total__c</fullName>
        <label>Sub Total</label>
        <summarizedField>QuoteLineItem.Sub_Total__c</summarizedField>
        <summaryFilterItems>
            <field>QuoteLineItem.Sales_Taxs__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>

Horizonriver QA20-Mar-2017/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Sales_Taxs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales Tax?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Total__c</fullName>
        <formula>Quantity *  UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Horizonriver QA20-Mar-2017/src/classes/QuoteDetailPageController.cls
public class QuoteDetailPageController {
    
    public Boolean DetailPage{get;set;}
    public Boolean EditPage{get;set;}
    public Boolean flg{get;set;}
    public quote qobj{get;set;}
    private List<QuoteLineItem> oppz;
    public id SelectedID{get;set;}
    
    public QuoteDetailPageController(ApexPages.StandardController controller) {
        EditPage = false;
        DetailPage = true;
        flg = false;
        qobj = [select id,Opportunity.Account.BillingPostalCode,Accountid,Account.name,ExpirationDate,name,IsSyncing,Status,opportunityid,opportunity.name,Contactid,PaymentTerms__c,DocusignStatus__c,DS_Envelope_del__c,Subtotal,Tax,Discount,ShippingHandling,TotalPrice,GrandTotal,QuoteFrom__c,Zip_Code__c from quote where id =: ApexPages.currentPage().getParameters().get('id')];
    }
    
    public List<QuoteLineItem> getOppz()
    {
        oppz = [SELECT Id, CreatedDate, Quantity, UnitPrice, QuoteId, Discount, Description, Product2Id,Product2.name, ListPrice, Subtotal, TotalPrice, Sales_Taxs__c, Sub_Total__c FROM QuoteLineItem where quoteid =: qobj.id ];
        return oppz;
    }

    public void DocuSign(){
        
        //return new PageReference('/apex/docusign_editenvelope?DSEID=a0pV00000016P68IAE&nw=0&SourceID=' + ApexPages.currentPage().getParameters().get('id'));
        
        //return new PageReference('https://dsfs.cs12.visual.force.com/apex/docusign_editenvelope?DSEID=a0pV00000016P68IAE&nw=0&SourceID=' + ApexPages.currentPage().getParameters().get('id'));
       // return null;
    }
    
    public pagereference Edit(){
        EditPage = true;
        DetailPage = false;
        return null;
    }
    
    public pagereference SaveBt(){
        EditPage = false;
        DetailPage = true;
        update qobj;
        return null;
    }
    
    public pagereference CancelBt(){
        EditPage = false;
        DetailPage = true;
        return null;
    }
    
    public pagereference CalTax(){
        Apexpages.standardcontroller sc = new Apexpages.standardcontroller(qobj);
        SureTaxController stc = new SureTaxController(sc);
        stc.login();
    return null;
    }    
    
    public pagereference Del(){
        system.debug('SelectedID==>'+ApexPages.currentPage().getParameters().get('accountId'));
        system.debug('SelectedID==>'+SelectedID);
        if(SelectedID != null){
            QuoteLineItem q = new QuoteLineItem();
            q.id = SelectedID;
            delete q;
        }
    return null;
    } 
    
    public pagereference Edits(){
    flg = true;
    return null;
    }
    
    public pagereference Saves(){
    flg = false;
    update oppz;
    return null;
    }
    
    
           
}